{"name": "test_two", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <py_test.test_py_02.TestClass object at 0x0000000003866320>\n\n    @pytest.mark.xfail()\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_py_02.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "9d71ac50-4180-4f8d-90c4-15c7bcc60316-attachment.txt", "type": "text/plain"}], "start": 1639444995295, "stop": 1639444995296, "uuid": "f6335daf-93bd-48b7-9c53-843828338aff", "historyId": "6c2bcb20a9b0e140b3abc73842ff2e26", "testCaseId": "0cea8fd259d4f8cc5db77e71bab7acb9", "fullName": "test_py_02.TestClass#test_two", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "suite", "value": "test_py_02"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "FXDN-20170826XB"}, {"name": "thread", "value": "4740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_py_02"}]}